# Generated by Django 3.2.7 on 2021-11-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videogames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('synopsis', models.CharField(max_length=1000000)),
                ('video', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=100000)),
                ('trailer', models.CharField(max_length=1000)),
            ],
        ),
    ]
